In [2]:
import torch
print(torch.__version__)

2.14.0+cu130


In [4]:
if torch.cuda.is_available():
    print("CUDA is available. You can use GPU acceleration.")
    print(f" {torch.cuda.get_device_name(torch.cuda.current_device())} is the current GPU.")

CUDA is available. You can use GPU acceleration.
 NVIDIA GeForce RTX 4060 Laptop GPU is the current GPU.


## Making Tensors

In [7]:
# empty
a=torch.empty(2, 3)

# shows whats in that memory location, not the actual values

In [9]:
type(a)

torch.Tensor

In [15]:
#Zeroes or ones
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [20]:
#seed+rand
torch.manual_seed(0)
torch.rand(2,3)

tensor([[0.4963, 0.7682, 0.0885],
        [0.1320, 0.3074, 0.6341]])

In [24]:
#My tensor
print(torch.tensor([[1, 2,4 ], [3, 4,5]]))

tensor([[1, 2, 4],
        [3, 4, 5]])


In [ ]:
#More ways to create tensors
print(torch.arange(0, 10, step=2)) # 0 to 10 with step of 2

#linspace
print(torch.linspace(0, 10, steps=5)) # 5 points between 0 and 1

print(torch.eye(3))  # identity matrix

print(torch.full((2, 3), 7))  # 2x3 matrix of sevens

tensor([0, 2, 4, 6, 8])
tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[7, 7, 7],
        [7, 7, 7]])


## Tensor shapes


In [34]:
#My tensor
x= torch.tensor([[1, 2,4 ], [3, 4,5]])

In [35]:
x.shape

torch.Size([2, 3])

In [40]:
a = torch.empty_like(x)
b= torch.zeros_like(x)

#all work except for rand
print(a)
print(b)

tensor([[    94018148038266,                  0,     94038554457968],
        [144677588273463296,                  0,                  0]])
tensor([[0, 0, 0],
        [0, 0, 0]])
